spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/warehouses}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:ahincho}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:10}
      minimum-idle: ${MIN_POOL_SIZE:2}
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      pool-name: HikariPool-1
      initialization-fail-timeout: 1
      validation-timeout: 5000
      leak-detection-threshold: 2000
      register-mbeans: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
springdoc:
  api-docs:
    path: ${SPRINGDOC_PATH:/api/docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_PATH:/api/swagger/}
    operations-sorter: method
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: INFO
server:
  port: ${SERVER_PORT:8080}